[31mCMake Error at /opt/ros/humble/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:59 (message):
  execute_process(/home/stoair/anaconda3/bin/python3 -m rosidl_adapter
  --package-name topic_interfaces --arguments-file
  /home/stoair/ros2CV/cv_ws/build/topic_interfaces/rosidl_adapter__arguments__topic_interfaces.json
  --output-dir
  /home/stoair/ros2CV/cv_ws/build/topic_interfaces/rosidl_adapter/topic_interfaces
  --output-file
  /home/stoair/ros2CV/cv_ws/build/topic_interfaces/rosidl_adapter/topic_interfaces.idls)
  returned error code 1:

  Error processing 'int x' of 'topic_interfaces/Coord': ''int' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$''

  Traceback (most recent call last):

    File "<frozen runpy>", line 198, in _run_module_as_main
    File "<frozen runpy>", line 88, in _run_code
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
                     ^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
             ^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 520, in parse_message_string
      Type(type_string, context_package_name=pkg_name),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 277, in __init__
      super(Type, self).__init__(
    File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_adapter/parser.py", line 205, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'int' is an invalid message
  name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:12 (rosidl_generate_interfaces)

[0m
gmake: *** [Makefile:747ï¼šcmake_check_build_system] é”™è¯¯ 1
